/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-PrayInPrayer-jkrAcb4IZxWCCdlP8-N9IuAGmUxjWwGs",
  "version": "2020-11-20"
}

export default ebconfig;